local harness=require("test.harness");local elatex=require("elatex")
harness.test("data/pinned-table-counts",function()
  local data=require("elatex.data");local errors=require("elatex.error")
  harness.equal(#data.keys,173);harness.equal(#data.environments,22);harness.equal(#data.delimiters,27)
  harness.equal(#data.combining_commands,50);harness.equal(#data.symbols,2916);harness.equal(#data.length_units,9)
  harness.equal(#data.combining_ranges,269);harness.equal(#data.wide_ranges,17);harness.equal(#data.full_width_ranges,5)
  harness.equal(#errors.records,38)
end)
harness.test("render/fraction",function() local result=elatex.render("\\frac{a}{b}");harness.equal(result.output,"a\n─\nb");harness.equal(result.error_state,0) end)
harness.test("render/nul",function() harness.equal(elatex.render("a\0b").output,"a") end)
harness.test("render/invalid-utf8",function() local ok,value=pcall(elatex.render,"\255");harness.truth(not ok and value.kind=="elatex.invalid_input") end)
harness.test("render/options",function() local ok,value=pcall(elatex.render,"a",{unknown=true});harness.truth(not ok and value.kind=="elatex.invalid_option" and value.name=="unknown") end)
harness.test("symbols/copy",function() local symbols=elatex.symbols();harness.equal(#symbols,2916);symbols[1].name="changed";harness.truth(elatex.symbols()[1].name~="changed") end)
harness.test("write/raw-byte-count",function() local seen="";local count,result=elatex.write("α",function(value) seen=value end);harness.equal(seen,"α");harness.equal(count,#seen);harness.equal(result.output,"α") end)
harness.test("errors/consume",function() local result=elatex.render("\\unknown");harness.equal(result.error_state,1);harness.equal(#elatex.take_errors(),0);harness.equal(elatex.error_state(),1) end)
harness.test("errors/render-text-publication",function() elatex.render_text("\\unknown");harness.equal(elatex.errors_string(),"Unknown command (1x)");harness.equal(elatex.error_state(),1);harness.equal(elatex.errors_string(),"") end)
harness.test("symbols/serialization",function() local handle=assert(io.open("test/fixtures/symbols.txt","rb"));local expected=handle:read("*a");handle:close();harness.equal(elatex.symbols_string(),expected) end)
harness.test("tree/single-unit",function() local tree=elatex.box_tree("a").output;harness.truth(tree:find("Type: UNIT\n      Content: a\n",1,true)~=nil);harness.equal(tree:sub(-1),"\n") end)
local function tagged_call(fn)
  local ok, value = pcall(fn)
  harness.truth(not ok and type(value) == "table" and value.kind)
  return value
end

harness.test("render/invalid-option-classes",function()
  harness.equal(tagged_call(function() elatex.render("a",false) end).kind,"elatex.invalid_option")
  harness.equal(tagged_call(function() elatex.render("a",{line_width=1.5}) end).name,"line_width")
  harness.equal(tagged_call(function() elatex.render("a",{font=1}) end).name,"font")
  harness.equal(tagged_call(function() elatex.render("a",{style="plain"}) end).name,"style")
  harness.equal(tagged_call(function() elatex.render("a",{wide_character_width=3}) end).name,"wide_character_width")
  harness.equal(tagged_call(function() elatex.render("a",{on_error=true}) end).name,"on_error")
end)

harness.test("render/negative-line-width",function()
  harness.equal(elatex.render("ab",{line_width=-1}).output,"ab")
end)

harness.test("render/error-callback-and-raise-order",function()
  local seen=false
  local result=elatex.render("\\unknown",{on_error=function(list) seen=list[1] end})
  harness.truth(seen=="Unknown command (1x)")
  harness.equal(result.error_state,1)
  local value=tagged_call(function() elatex.render("\\unknown",{raise_on_error=true,on_error=function() error("unexpected") end}) end)
  harness.equal(value.kind,"elatex.render_error")
end)

harness.test("write/object-sink",function()
  local sink={value=""}
  function sink:write(value) self.value=self.value..value end
  local bytes,result=elatex.write("α",sink)
  harness.equal(sink.value,"α")
  harness.equal(bytes,#"α")
  harness.equal(result.output,"α")
end)

harness.test("render-text/error-publication-is-consumable",function()
  elatex.render_text("\\unknown")
  harness.equal(elatex.errors_listing(),"ERROR: Unknown command (1x)\n")
  harness.equal(elatex.error_state(),1)
  harness.equal(elatex.take_errors()[1],nil)
end)
